### ISSUE TITLE
Support for inheritance in views to save typing

### ISSUE THREAD

**Issue by justingaylor** [rightscale/praxis-blueprints#12]
Something like this seems like a good approach:

```
view :link do
  attribute :id
  attribute :name
  attribute :href
end

view :default, inherit: :link do
  # everything from :tiny view
  attribute :foo
  attribute :bar
end

view :extended, inherit: :default do
  # everything from :default view (and recursively :tiny view)
  attribute :tags
end
```

Then at least we only define an attribute once. (as long as views are incremental)

**Comment by alikhajeh1** [comment]
+1

**Comment by justingaylor** [comment]
Some consideration should be given to what happens if an attribute is defined that is already in the parent view. In that case, overriding the inherited parent's attribute definition makes sense to me.

**Comment by blanquer** [comment]
Doing such a thing needs to handle circular references, and that's complex.
It is also not clear what the rules of priority of attribute definitions would be (especially if an attribute can be inherited 3 levels down, and overriden in a view from the middle...)

Anyway...I think that doing that is way to complicated and adds a bunch of unnecessary complexity for the gain.

doing exactly what you want is just as easy as:
```ruby
      view :my_view do
        schema.attributes.keys.map{|k| attribute k }
      end
```
I think that's perfectly reasonable no?

If anything, we could see about adding some better named function to get the key names of the attributes of the media_type...to avoid doing `schema.attributes.keys`. But even then...it's just 3 chaned methods instead of only one...

**Comment by alikhajeh1** [comment]
I didn't know about `schema.attributes.keys.map{|k| attribute k }` and am perfectly happy to use that, so I'll take back my +1 :)

**Comment by gampleman** [comment]
Wouldn't `view :default, attributes: :all` make sense as an option?

**Comment by blanquer** [comment]
@gampleman if that's what you want, you can use the `:master` view. It's always created for any blueprint because it is needed for things like example generation. It's not documented just because it only has internal use (although, we could easily document that fact if it seems useful). Be careful though, as many complex mediatype relationships do have cyclical loops, so one has to be careful about the views you use for rendering embed sub-attributes that are mediatypes themselves.

**Comment by careo** [comment]
We could support `inherit` as just sugar for copying the definition of an existing view. 

But how relevant/useful is this with the recent field expansion changes?

**Comment by gampleman** [comment]
Yeah I think we can close this issue.

**Comment by blanquer** [comment]
yup, its DSL built on Ruby, so helpers for less typing can be easily built for apps/devs that want that feature. I'm closing it.
If there's any strong feelings about this please re-open it and discuss some of the specific use cases.
