### ISSUE TITLE
Collection of same type causes stack level too deep

### ISSUE THREAD

**Issue by aliscott** [rightscale/praxis-blueprints#24]
With a blueprint that has an attribute that is a collection of the same type as the blueprint, we get a 'stack level too deep' error when defining the views.

Here's a failing spec for the issue: https://github.com/aliscott/praxis-blueprints/commit/6721caaff899d3fa02efc9e663be102aab8cc538

This is an example of the what we are using it for:
```ruby
class MetricsResult < Praxis::Blueprint

  attributes do
    attribute :group, Attributor::Hash.of(key: String, value: String)
    attribute :metrics, Metrics
    attribute :breakdown_metrics_results, Attributor::Collection.of(MetricsResult),
      description: 'The nested metric results requested by the `group` parameter.',
      example: []
  end

  view :default do
    attribute :group
    attribute :metrics
    attribute :breakdown_metrics_results
  end
end
```
Note: the data will not contain a loop

**Comment by blanquer** [comment]
After looking at it, the problem it is not only that the view defines an attribute of the same type (which is in the middle of its definition), but also when the view desired for the collection is the same view that you're in the middle of defining :)

So, double whammy because you're pointing to the `:default` view of the `MetricsResult` type, in the middle of defining the `:default` view of `MetricsResult` (which you're also in the middle of defining).

Anyway, I have PR 25 out to solve it all. :)
Thanks for reporting this interesting issue.
